<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_V01290</name>
   <tag></tag>
   <elementGuidId>d4eb3fa0-44c4-4726-b8a8-fbeec3e4e2c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.overflow-clip</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='pr_id_45-table']/tbody/tr/td/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f68fe470-1c06-45f3-b6af-f7183d38ecb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>overflow-clip</value>
      <webElementGuid>bfde89c8-7184-432d-abf9-10e8d974370f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>V01290</value>
      <webElementGuid>4b69243a-df32-4fb0-9b2c-50ec825afaa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_45-table&quot;)/tbody[@class=&quot;p-element p-datatable-tbody&quot;]/tr[@class=&quot;p-element p-selectable-row ng-star-inserted&quot;]/td[1]/div[@class=&quot;overflow-clip&quot;]</value>
      <webElementGuid>c7398404-6311-4347-9d85-854ace6fe84c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='pr_id_45-table']/tbody/tr/td/div</value>
      <webElementGuid>d5b8c4ac-7c1b-4be5-9a5d-ae1f9a33c77a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALAMAT 3'])[1]/following::div[1]</value>
      <webElementGuid>1d2e887c-15c8-4dc5-a5ea-df7be2b47a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALAMAT 2'])[1]/following::div[1]</value>
      <webElementGuid>943c1c43-adf8-4103-882c-5d16eb566bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PLN NUSANTARA POWER SERVICES. PT'])[1]/preceding::div[1]</value>
      <webElementGuid>15b131b3-43fd-4dc9-948e-1247829daaad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BANDARA JUANDA'])[1]/preceding::div[5]</value>
      <webElementGuid>406410dd-e048-4ca1-a938-9fb783fbee4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='V01290']/parent::*</value>
      <webElementGuid>754c5e18-d9bf-4013-9157-f69c204346ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div</value>
      <webElementGuid>5b2e1334-717a-4004-a23c-5a4c0f49e162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'V01290' or . = 'V01290')]</value>
      <webElementGuid>77b39d08-35c9-4e1c-8bec-1705425bd76d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
