<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_241A00 Pendapatan TL komponen A - Common</name>
   <tag></tag>
   <elementGuidId>82204ebe-cbb7-4321-8b28-c7b8fc091ddf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.p-treenode-content.p-treenode-selectable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='p-tabpanel-0']/p-tree/div/div/ul/p-treenode/li/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>005417b4-6bdf-421d-bc37-5aee6cba8296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>65f13aa5-a876-4ba4-bd99-2ecedf6295a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-treenode-content p-treenode-selectable</value>
      <webElementGuid>437b6286-d1a9-4992-b58a-60054ec88d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c32dde33-80bd-4e5e-a24f-1fbb07192ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a5a71fe2-7ec7-4d01-b9e5-ac08bc80679f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6a1793c3-8a93-4941-812e-4131de1d08f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bb00c030-92a2-4900-8d54-d40b7a99d010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>241A00 Pendapatan TL komponen A - Common</value>
      <webElementGuid>00f352fa-af3f-4f5f-9eb2-99c2b7585185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>241A00 Pendapatan TL komponen A - Common</value>
      <webElementGuid>9db7abcc-5913-4dd1-ad8e-f272fcc645b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-0&quot;)/p-tree[@class=&quot;p-element&quot;]/div[@class=&quot;ng-star-inserted p-tree p-component p-tree-selectable&quot;]/div[@class=&quot;p-tree-wrapper ng-star-inserted&quot;]/ul[@class=&quot;p-tree-container ng-star-inserted&quot;]/p-treenode[@class=&quot;p-element ng-star-inserted&quot;]/li[@class=&quot;p-treenode ng-star-inserted&quot;]/div[@class=&quot;p-treenode-content p-treenode-selectable&quot;]</value>
      <webElementGuid>aab53685-62d5-447e-82c2-152f08552c20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p-tabpanel-0']/p-tree/div/div/ul/p-treenode/li/div</value>
      <webElementGuid>a17418fa-43d2-45e7-8cc5-202e144f764c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahun'])[1]/following::div[4]</value>
      <webElementGuid>464d3dfb-7f1c-47d7-967f-676917655149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Distrik'])[1]/following::div[5]</value>
      <webElementGuid>bed4e3ca-6cef-4f32-a53f-bfd59220ac76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Distrik'])[2]/preceding::div[16]</value>
      <webElementGuid>fc7d2e14-5081-4e5a-984d-12375eb5d3c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahun'])[2]/preceding::div[17]</value>
      <webElementGuid>85183b48-3cb8-48ad-b1e3-1f011cc8a201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-treenode/li/div</value>
      <webElementGuid>d093546f-8698-4a11-a923-e18c4f9427a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '241A00 Pendapatan TL komponen A - Common' or . = '241A00 Pendapatan TL komponen A - Common')]</value>
      <webElementGuid>2294d121-da8f-4034-92e2-3faa457fd0c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
