<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Garansi_garansi (3)</name>
   <tag></tag>
   <elementGuidId>1df6dbe0-9d8c-4c04-b74a-3b3837dd1c8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#garansi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='garansi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c18d24dc-8c28-4f44-af73-fac97d3a0b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>9e305e8c-a32d-4f3b-86ed-814cdb8aba2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>garansi</value>
      <webElementGuid>9be57cd7-12ef-4ac3-a3ad-b793168e4ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>garansi</value>
      <webElementGuid>4d1facb7-6daa-4d46-9dd1-9adb0c11ddce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fd30eafc-2ee7-41ba-9898-dff34c2bce73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm text-color surface-overlay p-2 border-1 border-solid border-500 appearance-none outline-none focus:border-primary w-full h-custom ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>6764eabb-65e6-42c1-b34e-77c7f0351b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;garansi&quot;)</value>
      <webElementGuid>b9f9cfc8-430a-47ab-b031-29a93a24c73b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='garansi']</value>
      <webElementGuid>1abf0d8b-aedc-47da-bf01-a968474d16ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div[2]/input</value>
      <webElementGuid>0365cd1e-dcc9-44f5-8506-55d0428c68d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'garansi' and @placeholder = '0']</value>
      <webElementGuid>66777aeb-9675-4aba-a32e-44263599cf06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
