<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Keterangan_keterangan</name>
   <tag></tag>
   <elementGuidId>a641f6ea-6d8a-4658-ad4b-588b0d4a7e7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#keterangan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='keterangan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>783ac117-7ee4-403a-8070-f1750519d1c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>retensiKet</value>
      <webElementGuid>4790373a-ddb6-453a-8033-1a21dd5a0af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ad29555b-0bdc-4ca9-ae54-6c2cad83225b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>keterangan</value>
      <webElementGuid>20984022-a44c-4461-a76a-1805e097b14f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm text-color surface-overlay p-2 border-1 border-solid border-500 appearance-none outline-none focus:border-primary w-full ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>9978f150-1e0f-45d1-9398-19435926e11f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;keterangan&quot;)</value>
      <webElementGuid>3ac4a32b-eafe-4d2f-96a7-57c230e0f4c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='keterangan']</value>
      <webElementGuid>a323fe4e-8639-4277-8a36-2868cf894732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[3]/input</value>
      <webElementGuid>2082bbfc-a453-4260-8977-b4dc1558a3e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'keterangan']</value>
      <webElementGuid>a313cd64-348b-4c31-9849-e7f6033b2d9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
