<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Retensi_retensi (2)</name>
   <tag></tag>
   <elementGuidId>9c94cf72-ca7a-4dfc-989c-18a36f8283b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#retensi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='retensi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>158c7c06-eb6a-4943-b202-4cabb68ef5c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>77afd57c-9d08-4804-b459-381d3d4dd5f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>retensiPersen</value>
      <webElementGuid>4166a759-6b12-44e9-a8db-4e011b583e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>retensi</value>
      <webElementGuid>35ac2111-0883-4078-bd02-f0905ff18833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm text-color surface-overlay p-2 border-1 border-solid border-500 appearance-none outline-none focus:border-primary w-full ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>8d3b08f2-197f-49c9-94b3-9a9b46e0ec36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;retensi&quot;)</value>
      <webElementGuid>1d545b3f-136a-465f-a3e2-2979cbc57c0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='retensi']</value>
      <webElementGuid>0293e967-b723-49b4-a9ad-f6d54c73215c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>678df0f9-8469-4688-b6bc-edc430f7d3d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'retensi']</value>
      <webElementGuid>59e2565b-8958-4fc4-9bcf-61a84e77da1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
