<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Retensi_retensi (3) (1)</name>
   <tag></tag>
   <elementGuidId>8c4c6204-4117-49d0-b013-c287ee640bf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#retensi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='retensi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ed4aac2-1bc3-4e36-a8f8-db4dbfed3879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>b9b7d216-cb0c-4f42-99dc-55566ec04bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>retensiPersen</value>
      <webElementGuid>e6d3d2c5-a9eb-4f4d-b4f2-4168b33b7016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>retensi</value>
      <webElementGuid>69318d1f-8ffe-47f5-8477-c596dc45f774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm text-color surface-overlay p-2 border-1 border-solid border-500 appearance-none outline-none focus:border-primary w-full ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>944a4742-9201-425e-973f-662f87cebab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;retensi&quot;)</value>
      <webElementGuid>ce132a0e-1b8e-41dc-94ae-b417c3bde13b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='retensi']</value>
      <webElementGuid>d1d7ec8d-c324-4cea-9352-6c7f5863c4f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>35f51626-e458-40c3-ac95-dddb5ab597f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'retensi']</value>
      <webElementGuid>7295e4fc-0a5f-43b7-85e2-73a2680e2c35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
