<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User_userOa</name>
   <tag></tag>
   <elementGuidId>ab12517c-4196-4fe1-9814-1162e9b7662e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#userOa</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='userOa']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c18171d5-3658-475f-834f-1b14deb5f4a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userOa</value>
      <webElementGuid>e1c4160c-a27b-442a-b126-5d611d4f067e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>userOa</value>
      <webElementGuid>49845142-b0c0-4273-973f-0c4ad449bcaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>75b17ef0-e24a-4476-80aa-0a294292e511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm text-color surface-overlay p-2 border-1 border-solid border-500 appearance-none outline-none focus:border-primary w-full h-custom ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>5d6d4ffa-f518-4b13-837e-d71122d96bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userOa&quot;)</value>
      <webElementGuid>6e881b0e-09b3-4e1f-ae72-bdaece7a3ca4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='userOa']</value>
      <webElementGuid>1d8d71ad-dc34-4d61-99a2-a0ee1f895a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div[3]/input</value>
      <webElementGuid>7b52ff7a-cb83-4cc4-804b-930a81ad2c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'userOa' and @type = 'text']</value>
      <webElementGuid>85ce6dea-c82f-4e17-91ea-ecae59bd2d67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
