<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nilai PO_p-inputtext p-component p-el_bff212 (3) (1)</name>
   <tag></tag>
   <elementGuidId>f368eb85-8a38-40fa-98b6-31da76eb5a38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nilaiPo > span.p-inputnumber.p-component > input.p-inputtext.p-component.p-element.p-inputnumber-input.p-filled</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p-inputnumber[@id='nilaiPo']/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd1a4370-be92-4fee-91a1-be4d64420e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>9b5b0071-cd32-4d25-bb79-de445fef33d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-element p-inputnumber-input p-filled</value>
      <webElementGuid>15f03f91-caf9-4a5b-a4a1-11fe02b7173d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nilaiPo&quot;)/span[@class=&quot;p-inputnumber p-component&quot;]/input[@class=&quot;p-inputtext p-component p-element p-inputnumber-input p-filled&quot;]</value>
      <webElementGuid>0892b9de-70b3-4a18-866d-37d4fb0b5572</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p-inputnumber[@id='nilaiPo']/span/input</value>
      <webElementGuid>136316e7-48b4-4e38-854b-614c75f9ee91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/p-inputnumber/span/input</value>
      <webElementGuid>023f671a-2506-4568-92e4-b2ff70074798</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
