<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Retensi_retensi (1)</name>
   <tag></tag>
   <elementGuidId>bb7ebde2-4eec-48dc-b5be-46350875b80d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#retensi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='retensi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>193d99f3-ac13-4b6a-8517-22535e7c1e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c96de5df-f663-4068-a05f-7bc40d3b7986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>retensiPersen</value>
      <webElementGuid>263f2dc8-19c5-40c5-aaa6-5c106a77c298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>retensi</value>
      <webElementGuid>98035127-26fa-4311-82d4-7e4961b4d391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm text-color surface-overlay p-2 border-1 border-solid border-500 appearance-none outline-none focus:border-primary w-full ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>061b31a1-aff8-447c-ac19-7974e21243bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;retensi&quot;)</value>
      <webElementGuid>bc357f90-e8c0-472e-a201-e7455f79ac11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='retensi']</value>
      <webElementGuid>99ef885b-4180-4d84-9f2a-bc9ee592c903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>5a5b7cc8-6a9d-48b1-8765-775052787058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'retensi']</value>
      <webElementGuid>cfefe366-270a-4a3c-959c-435b1a54b323</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
