<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Satuan_satuan</name>
   <tag></tag>
   <elementGuidId>994ff740-30db-421e-8d4c-3633e778c031</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#satuan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='satuan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4dc2b157-5531-48b0-95db-26901196ccb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>satuan</value>
      <webElementGuid>1e992c47-10d6-4957-890a-c39369967fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>satuan</value>
      <webElementGuid>6d410f10-c70b-45f9-a127-3f17911ec02b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4f9a9ff4-f819-40fc-9d46-ed8039544bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm text-color surface-overlay p-2 border-1 border-solid border-500 appearance-none outline-none focus:border-primary w-full h-custom ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>7cb95905-0a6a-488a-a03f-b124d2a84c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;satuan&quot;)</value>
      <webElementGuid>3a668f10-c29e-4b9c-a5ea-4b67b6da7a51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='satuan']</value>
      <webElementGuid>7b2043bf-d267-4051-a16c-d4cdd41661be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[6]/div/div/input</value>
      <webElementGuid>e83031d8-ef69-48f5-9cf8-21e30d73307e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'satuan' and @type = 'text']</value>
      <webElementGuid>2e25ede1-0086-4c44-9aaf-c9aaea78a1b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
