<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Garansi_garansi (3) (1)</name>
   <tag></tag>
   <elementGuidId>8070671d-bb7b-4758-a9e4-0d9d30378867</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#garansi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='garansi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7475f5e8-0b70-4199-ab44-103023493374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>8204c375-ddfe-46cc-a6cd-21b4c201a4b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>garansi</value>
      <webElementGuid>0c5d507a-6ba8-4886-83df-e651ceba2b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>garansi</value>
      <webElementGuid>d978ebf1-e583-4894-8303-5d2552042dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>66cebe17-1837-47a5-b4ad-a4a3499a5183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm text-color surface-overlay p-2 border-1 border-solid border-500 appearance-none outline-none focus:border-primary w-full h-custom ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>c9a52e08-b265-495a-9f3d-113c26dc5bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;garansi&quot;)</value>
      <webElementGuid>9541d11a-8c9b-4768-a356-01906c58ed14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='garansi']</value>
      <webElementGuid>6d139ada-bc8f-4269-a1d9-ceb68fa0ac03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div[2]/input</value>
      <webElementGuid>45bf28af-ff1f-444d-9e09-2d262350acdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'garansi' and @placeholder = '0']</value>
      <webElementGuid>f6e6ee92-2884-414b-bff5-43f86b316105</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
