<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Keterangan_keterangan (1)</name>
   <tag></tag>
   <elementGuidId>c237fe16-8b32-48a1-92ec-8346743f224c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#keterangan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='keterangan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a550c621-5c6f-42de-8b47-40e242ea1d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>retensiKet</value>
      <webElementGuid>d1327de4-4505-486b-91a2-561b68a6d7b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9af4cc30-27dd-4891-b3f6-2c2f9ef8620b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>keterangan</value>
      <webElementGuid>a2ba7842-3ed9-41af-8585-c846a0a87871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm text-color surface-overlay p-2 border-1 border-solid border-500 appearance-none outline-none focus:border-primary w-full ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>b8ebb056-a0ef-4f55-a5dc-f9d50667e93e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;keterangan&quot;)</value>
      <webElementGuid>03e2a55d-5b8a-488f-a863-c1a91ba156ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='keterangan']</value>
      <webElementGuid>6d040bda-13b3-4e64-98f2-f296a3e4b7b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[3]/input</value>
      <webElementGuid>3cb189b4-1421-46e5-af69-e90660295882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'keterangan']</value>
      <webElementGuid>1150dcf3-00a8-4192-bb8b-e582667ca9f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
