<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Garansi_garansi (4)</name>
   <tag></tag>
   <elementGuidId>00410694-21d7-4d70-84e0-1e2ee29720c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#garansi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='garansi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8b64582-adc0-4ce2-ab4f-9cd735085408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>722306f6-7a37-4127-a09f-85fc1decf9f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>garansi</value>
      <webElementGuid>1fe8474b-5657-4d8c-a8bb-6c966869a95f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>garansi</value>
      <webElementGuid>0b9ce567-6ffa-4422-93e4-28767772aa40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e1f9a0ca-3541-4258-8eec-54752c3e4e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm text-color surface-overlay p-2 border-1 border-solid border-500 appearance-none outline-none focus:border-primary w-full h-custom ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>1117ba23-963b-4934-87a7-97ccad3dff46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;garansi&quot;)</value>
      <webElementGuid>0fad34a5-5ff4-487a-a5b6-c7f5e757b30f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='garansi']</value>
      <webElementGuid>e6891017-20c9-4b34-93e8-d57c2215afb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div[2]/input</value>
      <webElementGuid>0868e02b-4573-44d4-ba8c-ff017854b695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'garansi' and @placeholder = '0']</value>
      <webElementGuid>6b4dbf74-4502-4c8b-bbc7-17410f684406</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
