<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No OA_noOa</name>
   <tag></tag>
   <elementGuidId>b50e3999-2e39-48a5-a206-c0485dfa3fca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#noOa</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='noOa']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>385e904e-dfaf-44c2-974d-5435a0512557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>noOa</value>
      <webElementGuid>eaabab7f-10ec-4dd6-b6e4-264e9051c540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>noOa</value>
      <webElementGuid>447ce5df-cd03-4ca9-a9a7-68d3bcf41e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>61041e1c-f2bf-4b0b-ac41-bb6380d4c885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm text-color surface-overlay p-2 border-1 border-solid border-500 appearance-none outline-none focus:border-primary w-full h-custom ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>47bb3cff-1e5f-42bc-86f9-17a62bd2aae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;noOa&quot;)</value>
      <webElementGuid>e59edc0c-f599-438a-ade0-aa465468609b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='noOa']</value>
      <webElementGuid>360c6225-55cf-4f29-8fe7-bbc94eea0267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/input</value>
      <webElementGuid>27f8bdda-0b53-4961-97d9-07aa18485a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'noOa' and @type = 'text']</value>
      <webElementGuid>78e06e13-5659-4d16-83f2-db907b1d7619</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
