<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jumlah_jumlah</name>
   <tag></tag>
   <elementGuidId>b4aae2a5-6963-418d-b9d0-fbe31c08b981</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jumlah</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jumlah']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f762e5ee-7b93-491a-84cd-aca7c14c868e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>a80c17bf-b23c-4b33-ac58-64dcaa9a0861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-element p-inputnumber-input</value>
      <webElementGuid>09c22fdd-7111-49d0-b162-852848b3dfe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jumlah</value>
      <webElementGuid>cc05722b-f153-4d38-8070-d04139e30129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jumlah&quot;)</value>
      <webElementGuid>3720d832-f750-48a4-aec7-435a03595d45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jumlah']</value>
      <webElementGuid>11c952cf-2d74-47da-8a4f-50dfcb58e71e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/p-inputnumber/span/input</value>
      <webElementGuid>8ae18718-3566-4920-a3d7-e5ef7fd48dcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'jumlah']</value>
      <webElementGuid>589413f1-3c27-4aba-9036-ffdf83fc2095</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
