<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Harga Satuan_hrgSatuan</name>
   <tag></tag>
   <elementGuidId>b6c409fb-5779-4fb2-a436-0543b7e67747</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hrgSatuan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='hrgSatuan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d240b71a-9716-447a-989a-7762a214005c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>3d903549-d0a5-444a-8adc-4bd7496792ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-element p-inputnumber-input</value>
      <webElementGuid>b7045b82-a606-485e-894a-4a545a6deb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hrgSatuan</value>
      <webElementGuid>867e205a-2a3a-4aa7-9f34-5d7340e28439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hrgSatuan&quot;)</value>
      <webElementGuid>e74cdc41-fe6a-4d88-9efc-1c48ffe049cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hrgSatuan']</value>
      <webElementGuid>86d7013f-93e6-49e9-aac1-13d59bf312b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/p-inputnumber/span/input</value>
      <webElementGuid>c3d93671-17cc-4c89-9671-ea7c14499ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'hrgSatuan']</value>
      <webElementGuid>71c6baa8-92d5-4fba-bb98-4c9eaa5cdecc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
