<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_pelaksana 1_1</name>
   <tag></tag>
   <elementGuidId>54f7a9ef-c478-4408-8381-9701dfde4ebc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#p-highlighted-option</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='p-highlighted-option']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c9abc7da-5cdd-44a4-b073-f1072eefb836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>6aeb3e88-8ddc-4757-9d19-a692449cd47c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple p-element p-dropdown-item p-highlight</value>
      <webElementGuid>333fc87e-9603-4bce-93c7-b45eb28bb447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>p-highlighted-option</value>
      <webElementGuid>62e45f38-8ded-4a7d-ae20-5e4029789f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>pelaksana 1</value>
      <webElementGuid>17934968-b077-4afc-8dec-915e09dc299a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1744d9e2-d4aa-497c-929e-f73b5f53263f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>pelaksana 1</value>
      <webElementGuid>43d007f7-1fb5-47a7-b51c-e4c8264518f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-highlighted-option&quot;)</value>
      <webElementGuid>e66beace-cafe-4ef3-88d2-19b6e37eced9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='p-highlighted-option']</value>
      <webElementGuid>4fc81c87-3635-4be6-95fa-67ad97530982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pr_id_24_list']/p-dropdownitem[2]/li</value>
      <webElementGuid>91c94a11-5e5a-4126-9b2b-d1efaf85d87d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Pilih --'])[1]/following::li[1]</value>
      <webElementGuid>8a09ff35-d97e-4d1b-8ff7-24dc3946dda3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pelaksana 1'])[1]/following::li[2]</value>
      <webElementGuid>6dae3576-6a2b-4709-8e32-9f51c5fbad4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelaksana 3'])[1]/preceding::li[1]</value>
      <webElementGuid>63929c75-84cb-4532-9dab-717067a0d3b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-dropdownitem[2]/li</value>
      <webElementGuid>f2849086-fbf6-4acf-a94d-744cf1fe67ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'p-highlighted-option' and (text() = 'pelaksana 1' or . = 'pelaksana 1')]</value>
      <webElementGuid>8b1ad902-0d74-4776-8a41-76c9714e9897</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
