<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_USD - Nama United States Dollar_1</name>
   <tag></tag>
   <elementGuidId>997b1554-74ed-4551-9dce-4dd1ecf7532a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#p-highlighted-option</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='p-highlighted-option']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>7b18601a-828b-4ec6-acf2-a831f3bc4b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>78a29d23-7e51-463a-82e9-2d24090fb51e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple p-element p-dropdown-item p-highlight</value>
      <webElementGuid>8c5e0256-96af-4fb8-925f-ae27631bd486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>p-highlighted-option</value>
      <webElementGuid>9933ede9-22ce-4e2e-9951-370f26acafb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>USD - Nama United States Dollar</value>
      <webElementGuid>a47ff555-a42f-4bef-a2b5-0febe0554548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1962082b-5624-491b-b74c-68020efa40c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>USD - Nama United States Dollar</value>
      <webElementGuid>b8cebf0e-90df-4f50-a1e4-31c658afaf4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-highlighted-option&quot;)</value>
      <webElementGuid>8b65fa8b-a91c-4e4e-a6bc-8e28cf9beb5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='p-highlighted-option']</value>
      <webElementGuid>2e3b01ac-c850-4514-97c6-a28adb4121cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pr_id_22_list']/p-dropdownitem[2]/li</value>
      <webElementGuid>190c81ab-eb02-4d42-ba65-cd6f8047f793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Pilih --'])[1]/following::li[1]</value>
      <webElementGuid>d609e393-a851-4ac1-ad8e-87624341aa1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USD - Nama United States Dollar'])[1]/following::li[2]</value>
      <webElementGuid>180d26fd-cbe9-48e8-8132-1166d1030492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EUR - Euro'])[1]/preceding::li[1]</value>
      <webElementGuid>4056fdd6-4a38-4d21-9c99-2234805f4544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-dropdownitem[2]/li</value>
      <webElementGuid>c515f1c5-0616-410e-a020-51e84811eb95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'p-highlighted-option' and (text() = 'USD - Nama United States Dollar' or . = 'USD - Nama United States Dollar')]</value>
      <webElementGuid>8e7951ff-fded-4817-b010-d617fc229e70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
