<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sign In_p-ink p-ink-active (9)</name>
   <tag></tag>
   <elementGuidId>d2cfb504-7d79-403b-8949-1b32b8b88adc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.p-ink.p-ink-active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8418b5cc-cc65-4360-a530-324d3a28b556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ink p-ink-active</value>
      <webElementGuid>8f1e219b-8247-4643-b015-171ea908e210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/jhi-root[1]/jhi-logingw[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;background-login surface-ground h-screen w-screen flex align-items-center justify-content-center&quot;]/form[@class=&quot;ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;surface-card py-7 px-5 sm:px-7 shadow-2 flex flex-column w-11 sm:w-30rem&quot;]/div[4]/button[@class=&quot;p-element p-ripple mb-4 flex justify-content-center p-button p-component&quot;]/span[@class=&quot;p-ink p-ink-active&quot;]</value>
      <webElementGuid>0461aee7-2433-48e0-b5d2-10e0ef1a8d10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span[2]</value>
      <webElementGuid>8f52ef8b-cea6-4580-bdc5-6189ebfda70e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
