<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Not Authenticated_p-ink p-ink-active</name>
   <tag></tag>
   <elementGuidId>f5379063-fdd5-411f-b70e-c7a6b8c214c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.p-ink.p-ink-active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p-toastitem/div/div/button/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b8687e68-a062-4ea0-a9d8-0c32653df613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ink p-ink-active</value>
      <webElementGuid>696a5f94-1c23-408e-a2a7-0438c2c57c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/jhi-root[1]/p-toast[@class=&quot;p-element ng-tns-c64-0&quot;]/div[@class=&quot;ng-tns-c64-0 p-toast p-component p-toast-top-right&quot;]/p-toastitem[@class=&quot;p-element ng-tns-c63-1 ng-trigger ng-trigger-toastAnimation ng-tns-c64-0 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c63-1 ng-trigger ng-trigger-messageState p-toast-message-error p-toast-message&quot;]/div[@class=&quot;p-toast-message-content ng-tns-c63-1&quot;]/button[@class=&quot;p-ripple p-element p-toast-icon-close p-link ng-tns-c63-1 ng-star-inserted&quot;]/span[@class=&quot;p-ink p-ink-active&quot;]</value>
      <webElementGuid>40acfaf0-be23-4db4-ac39-2c12ff29e396</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-toastitem/div/div/button/span[2]</value>
      <webElementGuid>b9fc8f2c-1e36-4d93-9028-6c88766bdda7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
