<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_8</name>
   <tag></tag>
   <elementGuidId>328120c9-3eed-459a-bc57-76b1ad476158</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p-calendar[@id='retensiDate']/span/div/div/div/div[2]/table/tbody/tr[2]/td[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a850bb7d-8410-495a-bf29-6f6b4d9de4ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7a8fd5e1-93da-4308-a877-3db73a531926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple p-element ng-tns-c83-30 ng-star-inserted</value>
      <webElementGuid>a9c11c8e-85ec-4e2b-ae13-ec26b8a2eacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>d5af447f-c13f-4bff-ba98-4ffe4e71f9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;retensiDate&quot;)/span[@class=&quot;ng-tns-c83-30 p-calendar p-calendar-w-btn&quot;]/div[@class=&quot;ng-trigger ng-trigger-overlayAnimation ng-tns-c83-30 p-datepicker p-component ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-group-container ng-tns-c83-30 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-group ng-tns-c83-30 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-calendar-container ng-tns-c83-30 ng-star-inserted&quot;]/table[@class=&quot;p-datepicker-calendar ng-tns-c83-30&quot;]/tbody[@class=&quot;ng-tns-c83-30&quot;]/tr[@class=&quot;ng-tns-c83-30 ng-star-inserted&quot;]/td[@class=&quot;ng-tns-c83-30 ng-star-inserted&quot;]/span[@class=&quot;p-ripple p-element ng-tns-c83-30 ng-star-inserted&quot;]</value>
      <webElementGuid>aa0e8d3d-471d-481d-8a2d-36bc10f60f2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p-calendar[@id='retensiDate']/span/div/div/div/div[2]/table/tbody/tr[2]/td[2]/span</value>
      <webElementGuid>e3b69691-d507-437e-bd25-fd38b6634cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::span[17]</value>
      <webElementGuid>60f23e4e-2cc2-4d19-9873-ee696840a4ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::span[18]</value>
      <webElementGuid>7c97ea0b-0ea8-4838-81fe-b416b7340697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Garansi'])[1]/preceding::span[54]</value>
      <webElementGuid>6e45a90d-3a86-4ff2-9971-2984b7fe5c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Satuan'])[1]/preceding::span[54]</value>
      <webElementGuid>f0cdac7d-68b0-42ff-af05-ccae7286955d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='8']/parent::*</value>
      <webElementGuid>a0f39453-03e0-4c01-beff-07706f28119a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/span</value>
      <webElementGuid>e355911b-e3d8-4034-9258-3a6632d4aab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '8' or . = '8')]</value>
      <webElementGuid>16e631f3-5b2e-472f-a1df-5a710659d400</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
