<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sa_p-ink p-ink-active</name>
   <tag></tag>
   <elementGuidId>d4676dc4-3052-40a5-b9fb-ad68eaad71d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.p-ink.p-ink-active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[2]/td[5]/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d197c571-d5ca-493f-88da-4674d8aa0eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ink p-ink-active</value>
      <webElementGuid>25868163-ed37-4b81-9b5c-3925f8e8dd8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;ng-trigger ng-trigger-overlayAnimation ng-tns-c83-35 p-datepicker p-component ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-group-container ng-tns-c83-35 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-group ng-tns-c83-35 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-calendar-container ng-tns-c83-35 ng-star-inserted&quot;]/table[@class=&quot;p-datepicker-calendar ng-tns-c83-35&quot;]/tbody[@class=&quot;ng-tns-c83-35&quot;]/tr[@class=&quot;ng-tns-c83-35 ng-star-inserted&quot;]/td[@class=&quot;ng-tns-c83-35 p-datepicker-today ng-star-inserted&quot;]/span[@class=&quot;p-ripple p-element ng-tns-c83-35 ng-star-inserted&quot;]/span[@class=&quot;p-ink p-ink-active&quot;]</value>
      <webElementGuid>1c452203-9f06-4f06-830d-7f96711b7b59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[5]/span/span</value>
      <webElementGuid>4d16fff8-6510-4156-af24-e296c1bb6cce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
