<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_8 (2)</name>
   <tag></tag>
   <elementGuidId>ad0a6024-9a14-408a-aff5-a072e0e260b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p-calendar[@id='retensiDate']/span/div/div/div/div[2]/table/tbody/tr[2]/td[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>79a69e90-786f-4082-a155-891e0ee9c893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a3ab55b8-a695-4b7d-bf50-ce9e7860f561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple p-element ng-tns-c83-30 ng-star-inserted</value>
      <webElementGuid>8bdabd46-8164-409d-b5c0-f0cc640d8c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>1a2da8f3-5e88-4605-b51e-fca9abcca3fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;retensiDate&quot;)/span[@class=&quot;ng-tns-c83-30 p-calendar p-calendar-w-btn&quot;]/div[@class=&quot;ng-trigger ng-trigger-overlayAnimation ng-tns-c83-30 p-datepicker p-component ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-group-container ng-tns-c83-30 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-group ng-tns-c83-30 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-calendar-container ng-tns-c83-30 ng-star-inserted&quot;]/table[@class=&quot;p-datepicker-calendar ng-tns-c83-30&quot;]/tbody[@class=&quot;ng-tns-c83-30&quot;]/tr[@class=&quot;ng-tns-c83-30 ng-star-inserted&quot;]/td[@class=&quot;ng-tns-c83-30 ng-star-inserted&quot;]/span[@class=&quot;p-ripple p-element ng-tns-c83-30 ng-star-inserted&quot;]</value>
      <webElementGuid>e9cb9eee-dd81-4e5c-b84f-5e38f172a36a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p-calendar[@id='retensiDate']/span/div/div/div/div[2]/table/tbody/tr[2]/td[2]/span</value>
      <webElementGuid>9b591f9f-b814-4cb4-b8e3-391faa727af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::span[17]</value>
      <webElementGuid>ac3628f3-676e-4869-b503-c0961fa261fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::span[18]</value>
      <webElementGuid>e0379f82-0afa-45d3-8ba0-66239a14aa9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Garansi'])[1]/preceding::span[54]</value>
      <webElementGuid>35902cb5-40e6-4681-94d0-22371b5afae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Satuan'])[1]/preceding::span[54]</value>
      <webElementGuid>9161b513-ff41-480d-b381-ea6690ae9db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='8']/parent::*</value>
      <webElementGuid>2827b046-27ff-4bc5-9c63-b2cff8b153d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/span</value>
      <webElementGuid>8991157d-4cd1-4022-9f00-8aebcdd07a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '8' or . = '8')]</value>
      <webElementGuid>ea9a9736-a5ac-4bac-8395-c75cdb4b2eda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
