<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_ABL311013259960F101</name>
   <tag></tag>
   <elementGuidId>8b9c8088-8ae1-4a55-8300-a1ec94c92fbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.p-element.p-selectable-row.ng-star-inserted > td:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='pr_id_36-table']/tbody/tr/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>937c2d08-e677-4796-8bbe-21a4eea9ec18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ABL311013259960F101</value>
      <webElementGuid>d24bcb31-bcb0-4880-ac84-44aae3813fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_36-table&quot;)/tbody[@class=&quot;p-element p-datatable-tbody&quot;]/tr[@class=&quot;p-element p-selectable-row ng-star-inserted&quot;]/td[2]</value>
      <webElementGuid>5addc046-7314-41ef-a8c6-b1acb329bbbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='pr_id_36-table']/tbody/tr/td[2]</value>
      <webElementGuid>1d5eb326-e120-49e5-b328-5536f5fb737f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PJB2'])[1]/following::td[1]</value>
      <webElementGuid>981d7c23-4ce4-431b-b8d6-23b6d4150507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expel Desc'])[1]/following::td[2]</value>
      <webElementGuid>f7cfbc2c-1906-4f5e-bbe8-7afc0932a41d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SENIOR MANAGER/GM/MANAGER - PENGADAAN'])[1]/preceding::td[1]</value>
      <webElementGuid>ec68b4cb-b625-42b1-96d6-8f8e81a30049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jasa Borongan - Bangunan &amp; Kel. Halaman'])[1]/preceding::td[2]</value>
      <webElementGuid>27feebd3-3e0c-47ef-97e7-70ee3fca53d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ABL311013259960F101']/parent::*</value>
      <webElementGuid>10d1e7ff-2190-4f7f-a027-e93bd1310449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/td[2]</value>
      <webElementGuid>7422523b-c3fc-4e35-b931-4d4165a5bc03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'ABL311013259960F101' or . = 'ABL311013259960F101')]</value>
      <webElementGuid>95897ddf-8d73-40d8-b67d-bdb28d2947c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
