<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_PJB2 (4)</name>
   <tag></tag>
   <elementGuidId>7724e0a8-fcac-4a62-a4e2-c273ca395b00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.rowprk.ng-star-inserted > td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='pr_id_34-table']/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>288694db-b865-479e-91d3-8f0847fa5004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PJB2</value>
      <webElementGuid>27a0b7c4-cb40-4e0f-a8c4-d87672d9d037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_34-table&quot;)/tbody[@class=&quot;p-element p-datatable-tbody&quot;]/tr[@class=&quot;rowprk ng-star-inserted&quot;]/td[1]</value>
      <webElementGuid>3b20e9fb-8515-479b-b731-056efe80b65b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='pr_id_34-table']/tbody/tr/td</value>
      <webElementGuid>01b59da5-601e-4735-b811-9138ef0fb801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROJECT DESC'])[1]/following::td[1]</value>
      <webElementGuid>53decd78-1f56-4b88-a960-47bda9becbbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROJECT NO'])[1]/following::td[1]</value>
      <webElementGuid>bd02dd38-323c-466d-8fdb-b03ac9e29f1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pendapatan TL komponen A - Common'])[1]/preceding::td[2]</value>
      <webElementGuid>d9f69a45-eac7-440c-b259-2627de3bdef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PJB2'])[2]/preceding::td[3]</value>
      <webElementGuid>86334929-832d-4fb9-8cbc-44c9deea04bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PJB2']/parent::*</value>
      <webElementGuid>49486014-37cf-492a-900d-3215dc812683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/td</value>
      <webElementGuid>c8143453-215c-4627-b591-86f678f92419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'PJB2' or . = 'PJB2')]</value>
      <webElementGuid>a9e71d48-a214-4fe4-ab29-6e0b74b8edd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
