<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Uraian_uraian</name>
   <tag></tag>
   <elementGuidId>62b68582-afe1-4d8b-aafe-1a4edc3ca33a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uraian</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='uraian']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c99c2f90-c3cc-40c9-b3a3-422c27dff60b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uraian</value>
      <webElementGuid>14454aa3-18cd-46c0-966c-16065d38d80c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>uraian</value>
      <webElementGuid>a23e9b44-6001-4cca-a716-86415968d873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>76e74527-5ca3-4456-924b-86f843c59327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>77acd673-28b2-4731-bcf4-d8094524ede4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-base text-color surface-overlay p-2 border-1 border-solid border-500 appearance-none outline-none focus:border-primary w-full ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>b5356946-d348-413a-aae6-45e5be184cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uraian&quot;)</value>
      <webElementGuid>a2283d58-b96b-4717-a480-10268ba4224c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='uraian']</value>
      <webElementGuid>21b8d262-d368-438a-a6b4-b48db9397d23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/textarea</value>
      <webElementGuid>ee235988-1d0e-4801-938c-4d498df87a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'uraian' and @type = 'text']</value>
      <webElementGuid>e2721016-9a26-492c-8cb2-90c9baf94d44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
