<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Deskripsi_longdesc</name>
   <tag></tag>
   <elementGuidId>00116e58-42b4-4485-8674-f59c4e541035</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#longdesc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='longdesc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>48171228-9824-4914-a23d-637cf5f3665c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>longdesc</value>
      <webElementGuid>f6b297e6-870c-40fb-a78d-973485306d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>longdesc</value>
      <webElementGuid>d8c1a9df-2355-4e88-bfb8-0da3877df2f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e3308d6b-7259-446a-8dc3-8901b8bbfe40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>443330fc-be10-43be-8728-cca6d5131c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-base text-color surface-overlay p-2 border-1 border-solid border-500 appearance-none outline-none focus:border-primary w-full ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>0aa25900-c16b-475d-8f02-735b69f69f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;longdesc&quot;)</value>
      <webElementGuid>346bfa2d-0644-44ad-9fe4-df9950feaf98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='longdesc']</value>
      <webElementGuid>b478c727-5e08-464d-b9f8-4a1c12978c3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/textarea</value>
      <webElementGuid>27a87ef8-1143-4aa4-ac74-606f344c6480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'longdesc' and @type = 'text']</value>
      <webElementGuid>1012e8d4-bcf1-4232-94bd-628c9f9d5cfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
