<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Uraian_uraian (1)</name>
   <tag></tag>
   <elementGuidId>c8928619-adba-488c-b34e-353c68f5bfc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uraian</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='uraian']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ee265f0e-ab85-46cc-9284-221d8b040613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uraian</value>
      <webElementGuid>8edd75a1-b5f0-47ad-ae3a-58a7ae7709e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>uraian</value>
      <webElementGuid>770273a1-279b-4723-9cb7-487850e0ff31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e7a50a17-d162-45d1-be10-aa5520f3a442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>28368e87-465f-4976-8a7f-59e70c77a556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-base text-color surface-overlay p-2 border-1 border-solid border-500 appearance-none outline-none focus:border-primary w-full ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>0011e25e-02d2-4937-aa9c-0d532f32cb13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uraian&quot;)</value>
      <webElementGuid>13e7fd7a-4a3a-44a3-bd00-5c32b4977c44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='uraian']</value>
      <webElementGuid>bef335f0-88bf-4c79-a4fc-64bbbcdce3ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/textarea</value>
      <webElementGuid>782118f2-d67d-4949-b6ce-a27bf0864171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'uraian' and @type = 'text']</value>
      <webElementGuid>da541eb7-24d8-4af5-b657-cc95e46f8518</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
