<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Desk Kontrak_deskkontrak</name>
   <tag></tag>
   <elementGuidId>e3de4e1b-4cad-4d7a-8147-d86f6f3d6cac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#deskkontrak</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='deskkontrak']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d92f80b4-d2df-413f-8dca-7a9625f1c6be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>deskkontrak</value>
      <webElementGuid>86de6104-7b6f-4cfd-815b-2c9f18a9ef3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4bedd7bf-fe28-4b68-8357-5537b777e043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>deskKontrak</value>
      <webElementGuid>6560dfcc-acfd-4ca9-958c-8821c7f9c4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e4c71876-8d30-4c83-a4d7-b12519cff817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-base text-color surface-overlay p-2 border-1 border-solid border-500 appearance-none outline-none focus:border-primary w-full ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>c5e23280-1ca0-4610-b466-4fccabed75b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/jhi-root[1]/jhi-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;layout-container layout-static p-ripple-disabled layout-light&quot;]/div[@class=&quot;layout-content-wrapper&quot;]/div[@class=&quot;layout-content&quot;]/div[@class=&quot;layout-content-inner&quot;]/jhi-noncon-formgw[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;card&quot;]/form[@class=&quot;ng-valid ng-touched ng-dirty&quot;]/div[@class=&quot;grid -mx-1&quot;]/div[@class=&quot;col-7 px-1&quot;]/div[@class=&quot;field grid -mx-1&quot;]/div[@class=&quot;px-1 col&quot;]/textarea[@id=&quot;deskkontrak&quot;]</value>
      <webElementGuid>a3918ee5-bc0c-44cb-a670-1ab1e61842ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='deskkontrak']</value>
      <webElementGuid>7d341e72-f2d1-4d60-be03-3f1750c2405b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>a50066e9-3815-48fe-a1c3-5390611bc11a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'deskkontrak' and @type = 'text']</value>
      <webElementGuid>aee6c5f8-a4ca-4405-845a-13254d85592c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
